name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential

    - name: Build
      run: make

    - name: Run tests
      run: make check

    - name: Run distcheck
      run: make distcheck

