name: Kernel Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Makefile presence
      run: |
        ls -l
        if [ ! -f Makefile ]; then
          echo "Error: Makefile not found in the root directory"
          exit 1
        fi

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential linux-headers-$(uname -r) sparse

    - name: Build kernel module
      run: make

    - name: Run code style checks
      run: make check

    - name: Run static code analysis
      run: make sparse

    - name: Clean build artifacts
      run: make clean

